import { isIP } from "node:net";

// A missing target must never send a credential to a third-party service. Default to loopback;
// remote self-hosts pass their exact origin in the command generated by the dashboard.
export const DEFAULT_HMC_URL = "http://localhost:3000";
export const CONNECT_TIMEOUT_MS = 15_000;
// Pin the credential-reading helper to an immutable GitHub Release rather than the mutable default
// branch. Bump this alongside the package version when publishing a reviewed release.
export const PAIRING_NPX_COMMAND = "npx github:SeraphKc/how-much-ai#v0.1.0 connect";

export class HmcUrlError extends Error {
  constructor(message) {
    super(message);
    this.name = "HmcUrlError";
  }
}

export function serverErrorText(error, fallback, errorId) {
  const message = typeof error === "string" && error.trim() ? error.trim() : fallback;
  if (typeof errorId !== "string" || !/^err_[a-f0-9]{12}$/.test(errorId)) return message;
  const separator = /[.!?]$/.test(message) ? "" : ".";
  return `${message}${separator} Reference: ${errorId}.`;
}

function normalizedHostname(hostname) {
  const unbracketed = hostname.startsWith("[") && hostname.endsWith("]") ? hostname.slice(1, -1) : hostname;
  return unbracketed.toLowerCase().replace(/\.$/, "");
}

export function isLoopbackHostname(hostname) {
  const host = normalizedHostname(hostname);
  if (host === "localhost" || host.endsWith(".localhost")) return true;
  if (isIP(host) === 4) return Number(host.split(".")[0]) === 127;
  if (host === "::1") return true;

  // WHATWG URL canonicalizes an IPv4-mapped loopback such as ::ffff:127.0.0.1 to
  // ::ffff:7f00:1. Treat it as loopback too; other mapped addresses remain non-loopback.
  const mapped = host.match(/^::ffff:([0-9a-f]{1,4}):([0-9a-f]{1,4})$/);
  return !!mapped && (Number.parseInt(mapped[1], 16) >>> 8) === 127;
}

// WHATWG URL deliberately accepts several characters that are not valid in DNS hostnames, including
// shell metacharacters. Restrict targets to IP literals or conventional DNS-label syntax before an
// origin is ever rendered into a copy/paste command.
export function isSafeHostnameSyntax(hostname) {
  const host = normalizedHostname(hostname);
  if (isIP(host)) return true;
  if (!host || host.length > 253) return false;
  return host.split(".").every(
    (label) =>
      label.length > 0 &&
      label.length <= 63 &&
      /^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$/i.test(label),
  );
}

// The pairing target is an origin, not an arbitrary fetch URL. HTTPS is required whenever the token leaves
// the local machine; plain HTTP is useful only for a loopback development server. Returning the
// normalized origin prevents path/query/hash confusion when the pairing API path is appended.
export function parseHmcUrl(value) {
  const raw = typeof value === "string" && value.trim() ? value.trim() : DEFAULT_HMC_URL;
  if (raw.length > 2_048) throw new HmcUrlError("The pairing target URL is too long.");

  let url;
  try {
    url = new URL(raw);
  } catch {
    throw new HmcUrlError("The pairing target must be a valid absolute URL.");
  }

  if (url.username || url.password) throw new HmcUrlError("The pairing target must not include credentials.");
  if (url.search || url.hash) throw new HmcUrlError("The pairing target must not include a query string or fragment.");
  if (url.pathname !== "/") throw new HmcUrlError("The pairing target must be an origin without a path.");
  if (!isSafeHostnameSyntax(url.hostname)) {
    throw new HmcUrlError("The pairing target hostname contains unsupported characters.");
  }

  const loopbackHttp = url.protocol === "http:" && isLoopbackHostname(url.hostname);
  if (url.protocol !== "https:" && !loopbackHttp) {
    throw new HmcUrlError("The pairing target must use HTTPS (plain HTTP is allowed only for loopback development URLs).");
  }
  return url.origin;
}

// POSIX-safe single-quote encoding. The hostname parser already rejects shell metacharacters, but
// this second boundary keeps command rendering safe if a future origin format becomes broader.
export function shellSingleQuote(value) {
  return "'" + String(value).replaceAll("'", "'\"'\"'") + "'";
}

export function buildPairingCommand(code, target) {
  if (typeof code !== "string" || !/^[ABCDEFGHJKLMNPQRSTUVWXYZ23456789]{4}(?:-[ABCDEFGHJKLMNPQRSTUVWXYZ23456789]{4}){2}$/.test(code)) {
    throw new HmcUrlError("The pairing code is malformed.");
  }
  const origin = parseHmcUrl(target);
  return `HOW_MUCH_AI_URL=${shellSingleQuote(origin)} ${PAIRING_NPX_COMMAND} ${code}`;
}
